-- Required notebook parameter: catalog
CREATE CATALOG IF NOT EXISTS IDENTIFIER(:catalog);
USE CATALOG IDENTIFIER(:catalog);

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS features;
CREATE SCHEMA IF NOT EXISTS models;
CREATE SCHEMA IF NOT EXISTS semantic;
CREATE SCHEMA IF NOT EXISTS ops;
